#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

changedFiles="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

hasChanged() {
  echo "$changedFiles" | grep -q "$1"
}

if hasChanged 'yarn.lock'; then
  yarn
  yarn bootstrap
fi
