nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  "@chakra-ui/accordion@*":
    peerDependencies:
      "framer-motion": "*"
  "@chakra-ui/cli@*":
    peerDependencies:
      "typescript": "*"
  "@chakra-ui/skeleton@*":
    peerDependencies:
      "@chakra-ui/theme": "*"
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "@chakra-ui/switch@*":
    peerDependencies:
      "framer-motion": "*"
  "@mdx-js/loader@*":
    peerDependencies:
      "react": "*"
  "@storybook/core@*":
    peerDependencies:
      "webpack": "*"
  "@storybook/preset-create-react-app@*":
    peerDependencies:
      "react-refresh": "*"
      "react-scripts": "*"
      "typescript": "*"
      "webpack": "*"
  "react-dev-utils@*":
    peerDependencies:
      "typescript": "*"
      "webpack": "*"
