name: Release

on:
  push:
    paths:
      - ".changeset/**"
      - "packages/**"
      - "tools/**"
    branches:
      - main

jobs:
  release-ci:
    name: Run linter and tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint types and code
        run: pnpm run lint

      - name: Run jest
        run: pnpm run test:ci:cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build Packages
        run: pnpm run build

      - name: Create Release Pull Request or Publish to GitHub packages
        uses: changesets/action@master
        with:
          commit: "Update version and deploy packages"
          title: "Update version and deploy packages"
          publish: pnpm run changeset publish
          version: pnpm run changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build Storybook
        run: pnpm build:storybook

      - name: Deploy Storybook
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs-build
